export const UPDATE_ACTIVE_TAB = 'UPDATE_ACTIVE_TAB';
export const UPDATE_ORIGIN = 'UPDATE_ORIGIN';
export const UPDATE_ORIGIN_DATE = 'UPDATE_ORIGIN_DATE';

export const UPDATE_DESTINATION = 'UPDATE_DESTINATION';
export const UPDATE_DESTINATION_DATE = 'UPDATE_DESTINATION_DATE';

export const UPDATE_PASSENGER_COUNT = 'UPDATE_PASSENGER_COUNT';


export const DIRECT_FLIGHTS = 'DIRECT_FLIGHTS';
export const MULTI_CITY_FLIGHTS = 'MULTI_CITY_FLIGHTS';


export const RETURN_DIRECT_FLIGHTS = 'RETURN_DIRECT_FLIGHTS';
export const RETURN_MULTI_CITY_FLIGHTS = 'RETURN_MULTI_CITY_FLIGHTS';

export const UPDATE_RANGE = 'UPDATE_RANGE';
export const UPDATE_DIRECT_FLIGHT_SWITCH = 'UPDATE_DIRECT_FLIGHT_SWITCH';

export const FETCH_FLIGHTS = 'FETCH_FLIGHTS';